org.gradle.jvmargs=-Xmx2560m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
android.builtInKotlin=false
android.newDsl=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false

kotlin.code.style=official
kotlin.incremental=true
